export const restaurants = [
  {
    name: "Foodcourt 1",
    campusName: "Campus 10",
    cuisine: "Dosa, Idli, Sambhar, Vada, Sambar Rice",
    rating: "4.5",
    deliveryTime: "10",
    price: "200",
  },
  {
    name: "Foodcourt 2",
    campusName: "Campus 13",
    cuisine: "Pizza, Pasta, Garlic Bread, Salad",
    rating: "4.0",
    deliveryTime: "15",
    price: "350",
  },
  {
    name: "Foodcourt 3",
    campusName: "Campus 2",
    cuisine: "Burgers, Fries, Shakes, Onion Rings",
    rating: "4.7",
    deliveryTime: "12",
    price: "250",
  },
  {
    name: "Foodcourt 4",
    campusName: "Campus 5",
    cuisine: "Indian Thali, Raita, Chapati, Pickle",
    rating: "4.6",
    deliveryTime: "18",
    price: "300",
  },
  {
    name: "Foodcourt 5",
    campusName: "Campus 9",
    cuisine: "Noodles, Momos, Spring Rolls, Fried Rice",
    rating: "4.3",
    deliveryTime: "10",
    price: "150",
  },
  {
    name: "Foodcourt 6",
    campusName: "Campus 12",
    cuisine: "Wraps, Sandwiches, Smoothies, Fries",
    rating: "4.2",
    deliveryTime: "8",
    price: "180",
  },
  
  {
    name: "Foodcourt 7",
    campusName: "Campus 18",
    cuisine: "Sushi, Ramen, Tempura, Miso Soup",
    rating: "4.8",
    deliveryTime: "20",
    price: "400",
  },
  {
    name: "Foodcourt 8",
    campusName: "Campus 6",
    cuisine: "Burritos, Tacos, Quesadillas, Nachos",
    rating: "4.4",
    deliveryTime: "15",
    price: "250",
  },
 
];
